load("@hedron_compile_commands//:refresh_compile_commands.bzl", "refresh_compile_commands")

# package(default_visibility = ["//visibility:public"])

# filegroup(
#     name = "resources",
#     srcs = glob(["resources/**"]),
#     visibility = ["//visibility:public"],
# )

refresh_compile_commands(
    name = "refresh",
    targets = {
        "//ex6-wgpu-glfw:all": "",
    },
)
